miltonproject03final/miltontours/models.py
from . import db

class City(db.Model):
    __tablename__='cities'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False, default = 'defaultcity.jpg')
    tours = db.relationship('Tour', backref='City', cascade="all, delete-orphan")

    def __repr__(self):
        str = "Id: {}, Name: {}, Description: {}, Image: {}\n" 
        str =str.format( self.id, self.name,self.description,self.image)
        return str

orderdetails = db.Table('orderdetails', 
    db.Column('order_id', db.Integer,db.ForeignKey('orders.id'), nullable=False),
    db.Column('tour_id',db.Integer,db.ForeignKey('tours.id'),nullable=False),
    db.PrimaryKeyConstraint('order_id', 'tour_id') )

class Tour(db.Model):
    __tablename__='tours'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64),nullable=False)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False)
    price = db.Column(db.Float, nullable=False)
    date = db.Column(db.DateTime, nullable=False)
    city_id = db.Column(db.Integer, db.ForeignKey('cities.id'))
    
    def __repr__(self):
        str = "Id: {}, Name: {}, Description: {}, Image: {}, Price: {}, City: {}, Date: {}\n" 
        str =str.format( self.id, self.name,self.description,self.image, self.price, self.city_id, self.date)
        return str

class Order(db.Model):
    __tablename__='orders'
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.Boolean, default=False)
    firstname = db.Column(db.String(64))
    surname = db.Column(db.String(64))
    email = db.Column(db.String(128))
    phone = db.Column(db.String(32))
    totalcost = db.Column(db.Float)
    date = db.Column(db.DateTime)
    tours = db.relationship("Tour", secondary=orderdetails, backref="orders")
    
    def __repr__(self):
        str = "id: {}, Status: {}, Firstname: {}, Surname: {}, Email: {}, Phone: {}, Date: {}, Tours: {}, Total Cost: {}\n" 
        str =str.format( self.id, self.status,self.firstname,self.surname, self.email, self.phone, self.date, self.tours, self.totalcost)
        return str

miltonproject03final/miltontours/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField
from wtforms.validators import InputRequired, email

# form used in basket
class CheckoutForm(FlaskForm):
    firstname = StringField("Your first name", validators=[InputRequired()])
    surname = StringField("Your surname", validators=[InputRequired()])
    email = StringField("Your email", validators=[InputRequired(), email()])
    phone = StringField("Your phone number", validators=[InputRequired()])
    submit = SubmitField("Send to Agent")


miltonproject03final/miltontours/__init__.py
#import flask - from the package import class
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

db=SQLAlchemy()
app=Flask(__name__)

#create a function that creates a web application
# a web server will run this web application
def create_app():
    app.debug=True
    app.secret_key='BetterSecretNeeded123'

    #set the app configuration data 
    app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///milton.sqlite'

    #initialize db with flask app
    db.init_app(app)

    bootstrap = Bootstrap(app)
    
    #importing modules here to avoid circular references, register blueprints of routes
    from . import views
    app.register_blueprint(views.bp)
    #from . import admin
    #app.register_blueprint(admin.bp)
   
    return app

@app.errorhandler(404) 
# inbuilt function which takes error as parameter 
def not_found(e): 
  return render_template("404.html")

@app.errorhandler(500)
def internal_error(e):
  return render_template("500.html")


miltonproject03final/miltontours/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import City, Tour, Order
from datetime import datetime
from .forms import CheckoutForm
from . import db


bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    cities = City.query.order_by(City.name).all()
    return render_template('index.html', cities = cities)

@bp.route('/tours/<int:cityid>/')
def citytours(cityid):
    tours = Tour.query.filter(Tour.city_id == cityid)
    return render_template('citytours.html', tours = tours)


# Referred to as "Basket" to the user
@bp.route('/order', methods=['POST','GET'])
def order():
    tour_id = request.values.get('tour_id')

    # retrieve order if there is one
    if 'order_id'in session.keys():
        order = Order.query.get(session['order_id'])
        # order will be None if order_id stale
    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order(status = False, firstname='', surname='', email='', phone='', totalcost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('failed at creating a new order')
            order = None
    
    # calcultate totalprice
    totalprice = 0
    if order is not None:
        for tour in order.tours:
            totalprice = totalprice + tour.price
    
    # are we adding an item?
    if tour_id is not None and order is not None:
        tour = Tour.query.get(tour_id)
        if tour not in order.tours:
            try:
                order.tours.append(tour)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your basket'
            return redirect(url_for('main.order'))
        else:
            flash('item already in basket')
            return redirect(url_for('main.order'))
    
    return render_template('order.html', order = order, totalprice = totalprice)


# Delete specific basket items
@bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id=request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        tour_to_delete = Tour.query.get(id)
        try:
            order.tours.remove(tour_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))


# Scrap basket
@bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.index'))


@bp.route('/checkout', methods=['POST','GET'])
def checkout():
    form = CheckoutForm() 
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
       
        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            totalcost = 0
            for tour in order.tours:
                totalcost = totalcost + tour.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('Thank you! One of our awesome team members will contact you soon...')
                return redirect(url_for('main.index'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form = form)

miltonproject03final/miltontours/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Milton Tours</title>
    <meta name="description" content="Milton Tours">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- an example of using css alongside bootstrap -->
    <style>
        /* to place border around items in the shopping basket - orders.html */
        .my-row {
            border: 1px solid grey;
        }
    </style>
</head>

<body>
    <!-- putting header inside container will prevent full width navbar -->

    <header>

        <!--navbar creates a navigation bar -->
        <!-- Colours https://getbootstrap.com/docs/4.0/utilities/colors/ -->

        <nav class="navbar navbar-expand-lg navbar-light bg-info">

            <a class="navbar-brand text-light" href="{{ url_for('main.index') }}">
                <img src="{{url_for('static', filename='img/miltonlogo.png')}}" width="30" height="30" class="d-inline-block align-top"
                    alt="Milton Tours Logo">
                Milton Tours
            </a>

            <!-- create a button for collapsing the menu -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">

                <!-- individual menu item-->
                <a class="nav-item nav-link text-light active" href="#">About Us</a>

                <!-- individual menu item-->
                <a class="nav-item nav-link text-light" href="{{url_for('main.index', _anchor='cities_anchor')}}">Cities</a>

                <!-- individual menu item-->
                <a class="nav-item nav-link text-light" href="{{url_for('main.order')}}">Basket</a>

                <!-- individual menu item-->
                <!-- this link will fail but good test of the 404 handler -->
                <a class="nav-item nav-link text-light" href="discounts.html">Offers</a>

                <!-- right aligned menu items thanks to ml-auto -->
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item active">
                        <!-- text like phone number -->
                        <span class="navbar-text text-light">1-800-MILTON</span>
                    </li>
                    <li class="nav-item">
                        <!-- search box -->
                        <form class="form-inline my-2 my-lg-0 ml-5">
                            <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-black btn btn-secondary btn-s my-0 ml-1"
                                type="submit">Search</button>
                        </form>
                    </li>
                </ul>

        </nav>

        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-primary" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
            </div>
        {% endif %}
        {% endwith %} 

        {% block head %}{% endblock %}

    </header>


    <!-- main page content goes in container -->
    <div class="container-fluid">
        <main>
            {% block main %}{% endblock %}
        </main>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container text-center">
            <p>Copyright &copy; Milton Tours</p>
        </div>
    </footer>
    <!-- Footer -->


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>

</html>

miltonproject03final/miltontours/templates/checkout.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block main %}
    <section>  
        <div class="container">
            <div class="row">
                <div class = "col-12">
                    <h1>Checkout</h1>
                    <p>
                        Thank you for your interest. Please provide your details so that one of our awesome tour agents can contact you to finalise details and take payment. Thank you! 
                    </p>
                </div>
            </div>
            <div class="row">
                <div class = "col-6">
                    {{wtf.quick_form(form)}}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

miltonproject03final/miltontours/templates/citytours.html
{% extends 'base.html' %}

{% block main %}
<!-- display tours for the specific city -->
<section>

    <div class="text-dark text-center">
        <div>
            <p class="h3 text-dark mb-4">Select a tour from below</p>
        </div>
    </div>

    <div class="card-columns">
        <!-- each tour is a bootstrap card -->
        {% for tour in tours%}
        <div class="card">
            <img class="card-img-top" src="{{url_for('static', filename='img/'+tour.image)}}" alt="Card image">
            <div class="card-body">
                <h4 class="card-title">{{tour.name}}</h4>
                <p class="card-text">{{tour.description}}</p>
            </div>
            <div class="card-footer">
                <form action="{{ url_for('main.order') }}">
                    <input type="hidden" id="tour_id" name="tour_id" value="{{ tour.id }}">
                    <input class="btn btn-primary" type="submit" value="Add to Basket">
                </form>
            </div>
        </div>
        {% endfor %}
    </div>

</section>
{% endblock %}


miltonproject03final/miltontours/templates/index.html
{% extends 'base.html' %}

{% block head %}
<!-- add a big banner to welcome user -->
<div class="jumbotron jumbotron-fluid card card-image" style="background-image: url({{url_for('static', filename='img/header.jpg')}});">
    <div class="text-white text-center py-5 px-4">
        <div>
            <h1 class="display-2">Welcome to Milton Tours</h1>
            <p class="display-4 text-dark">You need a vacation!</p>
        </div>
    </div>
</div>
{% endblock %}

{% block main %}
<!-- marketing information -->
<section>
    <div class="container">
        <div class="text-white text-center">
            <div>
                <p class="h1 text-dark mb-4">Why us?</p>
            </div>
        </div>
        <!-- CSS Grid -->
        <div class="row">
            <div class="col-md-6">
                <article>
                    <h2>Beautiful locations</h2>
                    <p>We have tours in some of the best locations all around Australia:</p>
                    <ul>
                        <li>Close to city center</li>
                        <li>Free shuttle service to Airport</li>
                        <li>Helpful staff</li>
                    </ul>
                </article>

            </div>
            <div class="col-md-6">
                <article>
                    <h2>Affordable selections</h2>
                    <p>We have <span> great prices and offers </span> all year round!</p>
                    <p>Click <a href="discounts.html">here</a> for more information.</p>
                </article>
            </div>
        </div>
        <!-- Horizontal Rule -->
        <hr>
    </div>
</section>

<!-- display the cities to the user -->
<section>
    <div class="text-dark text-center">
        <div>
            <p class="h3 text-dark mb-4" id="cities_anchor">Pick a city to see what we have to offer!</p>
        </div>
    </div>
    <div class="card-deck">

        {% for city in cities%}
        <div class="card">
            <img class="card-img-top" src="{{url_for('static', filename='img/'+city.image)}}" alt="Card image">
            <div class="card-body">
                <h4 class="card-title">{{city.name}}</h4>
                <p class="card-text">{{city.description}}</p>
            </div>
            <div class="card-footer"><a href= "{{ url_for('main.citytours', cityid=city.id) }}" class="btn btn-primary">Tours</a></div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}


miltonproject03final/miltontours/templates/order.html
{% extends 'base.html' %}

{% block main %}
<!-- display contents of user basket -->
<section>  
    <div class="container">
        <div class="row co-12 d-flex mt-2 mb-2">
            <h3>Shopping Basket</h3>
        </div>
        <!-- each tour on seperate row -->
        {% for tour in order.tours %}
            <div class="row shadow-md my-row mb-3">
                <div class="col-sm-10 card">
                    <h5 class="card-header">{{tour.date.strftime("%d-%m-%Y")}} : {{tour.City.name}} {{tour.name}}</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-2">
                                <img class="img-thumbnail" src="{{url_for('static', filename=('img/' + tour.image))}}">
                            </div>
                            <div class="col-10">
                                <!-- Item Description -->
                                <p class="card-text">{{tour.description}}</p>   
                            </div>  
                        </div>                      
                    </div>
                </div>
                <br><br>
                <!-- right column has price and delete button -->
                <div class="col-sm-2">
                    <!-- delete item button -->
                        <h5>{{ "$%.2f"|format(tour.price) }}</h5>
                        <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                            <input type="hidden" id="id" name="id" value="{{tour.id}}">
                            <input type="submit" value="Delete" class="btn btn-primary mb-3">
                        </form> 
                </div>
            </div>
        {% endfor %}
        
        <!-- total price and page controls -->
        <section>
            <div class="row co-12 d-flex">
                <h5 class="mt-4">Quote = {{ "$%.2f"|format(totalprice) }}</h5>
            </div>
        
            <div class="row co-12 d-flex mt-2 mb-4">
                <a href="{{ url_for('main.index', _anchor='cities_anchor') }}" class="btn btn-primary mr-4">Cities</a>
                <a href="{{ url_for('main.checkout') }}" class="btn btn-primary mr-4">Checkout</a>
                <a href="{{ url_for('main.deleteorder') }}" class="btn btn-primary">Empty Basket</a>
            </div>
        </section>
    </div>
</section>
{% endblock %}
